export interface ITransport {
  "appId": number,
  "transpNum": string,
  "vehicle": {
    "appTranspId": string,
    "vin": string,
    "transpBody": string,
    "transpChassis": string,
    "transpMadeDate": string,
    "transpEngine": string,
    "colorStr": string,
    "transpWeight": number,
    "transpMaxWeight": number,
    "passengerSeatsNum": number,
    "recDate": Date | string,
    "transpId": string,
    "powerHorse": null,
    "powerWatt": null,
    "engineVolume": null,
    "modification": null,
    "ttranspModel": null,
    "ctranspModel": null,
    "ttranspType": null,
    "ctranspType": null,
    "tbodyType": null,
    "cbodyType": null,
    "tspecType": null,
    "cspecType": null,
    "ttranspCategory": null,
    "ctranspCategory": null,
    "ttranspEkoClass": null,
    "ctranspEkoClass": null,
    "ttransmissionType": null,
    "ctransmissionType": null,
    "tengineType": null,
    "cengineType": null,
    "twheelDrive": null,
    "cwheelDrive": null,
    "thandDrive": null,
    "chandDrive": null
  },
  "person": null,
  "license": null
}